services:
  web:
    image: ghcr.io/replicatedhq/ttlsh-web:latest
    build:
      context: web
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    container_name: ttlsh-web
    restart: always
    pull_policy: always
    ports:
      - "3000:3000"
    networks:
      - ttlsh-network

  registry:
    image: ghcr.io/replicatedhq/ttlsh-registry:latest
    build:
      context: registry
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    container_name: ttlsh-registry
    restart: always
    pull_policy: always
    env_file: ".env"
    environment:
      - PORT=5000
      - HOOK_TOKEN=${HOOK_TOKEN:-placeholder}
      - HOOK_URI=http://hooks:8000/v1/hook/registry-event
      - REPLREG_HOST=localhost:5000
      - REPLREG_SECRET=placeholder
      - S3_REGION=us-east-1
      - S3_BUCKET=ttlsh
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - minio
    networks:
      - ttlsh-network

  minio:
    image: minio/minio
    container_name: ttlsh-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio/data:/data
    networks:
      - ttlsh-network
    command: server /data --console-address ":9001"

  hooks:
    image: ghcr.io/replicatedhq/ttlsh-hooks:latest
    build:
      context: hooks
      dockerfile: Dockerfile.hooks
      platforms:
        - "linux/amd64"
    container_name: ttlsh-hooks
    restart: always
    pull_policy: always
    env_file: ".env"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - ttlsh-network

  reaper:
    image: ghcr.io/replicatedhq/ttlsh-reaper:latest
    build:
      context: hooks
      dockerfile: Dockerfile.reap
      platforms:
        - "linux/amd64"
    container_name: ttlsh-reaper
    restart: always
    pull_policy: always
    env_file: ".env"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - ttlsh-network

  auth:
    image: ghcr.io/replicatedhq/ttlsh-auth:latest
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: ttlsh-auth
    restart: always
    env_file: ".env"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - VALIDATION_SERVICE_URL=${VALIDATION_SERVICE_URL}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
    ports:
      - "8080:8080"
    networks:
      - ttlsh-network

  redis:
    image: redis:8.5-alpine
    container_name: ttlsh-redis
    restart: always
    pull_policy: always
    env_file: ".env"
    ports:
      - "6379:6379"
    networks:
      - ttlsh-network
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  postgres:
    image: postgres:17-alpine
    container_name: ttlsh-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ttlsh}
      - POSTGRES_USER=${POSTGRES_USER:-ttlsh_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - ttlsh-network

networks:
  ttlsh-network:
    driver: bridge
