apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "aocr.fullname" . }}-reaper
  labels:
    {{- include "aocr.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.reaper.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reaper
            image: "{{ .Values.image.repository }}/aocr-reaper:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: REGISTRY_URL
              value: "http://{{ include "aocr.fullname" . }}-registry"
            - name: REAPER_RUN_ONCE
              value: "true"
            - name: POSTGRES_HOST
              value: {{ default (printf "%s-postgres" (include "aocr.fullname" .)) .Values.postgres.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aocr.fullname" . }}-secrets
                  key: postgres-password
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: {{ printf "%s-redis" (include "aocr.fullname" .) | quote }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aocr.fullname" . }}-secrets
                  key: redis-password
            {{- end }}
            {{- if .Values.reaper.repositoryIds }}
            - name: REPOSITORY_IDS
              value: {{ join "," .Values.reaper.repositoryIds | quote }}
            {{- end }}
          restartPolicy: OnFailure
