apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aocr.fullname" . }}-redis
  labels:
    {{- include "aocr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aocr.name" . }}-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aocr.name" . }}-redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        command: ["/bin/sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\""]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "aocr.fullname" . }}-secrets
              key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aocr.fullname" . }}-redis
spec:
  ports:
  - port: 6379
  selector:
    app.kubernetes.io/name: {{ include "aocr.name" . }}-redis
