apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aocr.fullname" . }}-registry-config
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      formatter: text
    storage:
      delete:
        enabled: true
      s3:
        region: {{ .Values.registry.s3.region }}
        bucket: {{ .Values.registry.s3.bucket }}
        regionendpoint: {{ .Values.registry.s3.endpoint }}
        v4auth: true
        rootdirectory: /
    http:
      addr: 0.0.0.0:{{ .Values.registry.port }}
      secret: "placeholder-secret"
      host: {{ .Values.global.domain }}
    auth:
      token:
        realm: "https://{{ .Values.global.domain }}/v2/token"
        service: "aocr"
        issuer: "aocr-auth"
        rootcertbundle: /etc/docker/registry/auth.crt
    notifications:
      endpoints:
        - name: registry-hooks
          url: http://{{ include "aocr.fullname" . }}-hooks:8000/v1/hook/registry-event
          timeout: 1s
          threshold: 10
          backoff: 1s
