apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ttlsh.fullname" . }}-postgres
  labels:
    {{- include "ttlsh.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ttlsh.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ttlsh.name" . }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ttlsh.name" . }}-postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "ttlsh.fullname" . }}-secrets
              key: postgres-password
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: {{ include "ttlsh.fullname" . }}-db-init
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttlsh.fullname" . }}-postgres
spec:
  ports:
  - port: 5432
  selector:
    app.kubernetes.io/name: {{ include "ttlsh.name" . }}-postgres
