apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ttlsh.fullname" . }}-reaper
  labels:
    {{- include "ttlsh.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.reaper.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reaper
            image: "{{ .Values.image.repository }}/ttlsh-reaper:{{ .Values.image.tag }}"
            env:
            - name: REGISTRY_URL
              value: "http://{{ include "ttlsh.fullname" . }}-registry"
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.user }}:$(POSTGRES_PASSWORD)@{{ include "ttlsh.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ttlsh.fullname" . }}-secrets
                  key: postgres-password
          restartPolicy: OnFailure
