apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ttlsh.fullname" . }}-registry
  labels:
    {{- include "ttlsh.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ttlsh.name" . }}-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ttlsh.name" . }}-registry
    spec:
      containers:
      - name: registry
        image: "{{ .Values.image.repository }}/ttlsh-registry:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.registry.port }}
        env:
        - name: PORT
          value: "{{ .Values.registry.port }}"
        - name: REPLREG_HOST
          value: "{{ .Values.global.domain }}"
        - name: S3_REGION
          value: {{ .Values.registry.s3.region | quote }}
        - name: S3_BUCKET
          value: {{ .Values.registry.s3.bucket | quote }}
        - name: S3_ENDPOINT
          value: {{ .Values.registry.s3.endpoint | quote }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "ttlsh.fullname" . }}-secrets
              key: s3-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "ttlsh.fullname" . }}-secrets
              key: s3-secret-key
        - name: HOOK_URI
          value: "http://{{ include "ttlsh.fullname" . }}-hooks:8000/v1/hook/registry-event"
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry/config.yml
          subPath: config.yml
        - name: auth-crt
          mountPath: /etc/docker/registry/auth.crt
          subPath: auth.crt
      volumes:
      - name: config
        configMap:
          name: {{ include "ttlsh.fullname" . }}-registry-config
      - name: auth-crt
        secret:
          secretName: {{ include "ttlsh.fullname" . }}-secrets
          items:
          - key: jwt-public-key
            path: auth.crt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttlsh.fullname" . }}-registry
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.registry.port }}
  selector:
    app.kubernetes.io/name: {{ include "ttlsh.name" . }}-registry
