apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ttlsh.fullname" . }}-secrets
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  # You should provide these as base64 encoded strings in your values or via --set
  jwt-private-key: {{ default "" .Values.auth.jwtPrivateKey | b64enc | quote }}
  jwt-public-key: {{ default "" .Values.auth.jwtPublicKey | b64enc | quote }}
  gcs-key: {{ default "" .Values.registry.gcs.key | b64enc | quote }}
